version: '3'

tasks:
  run:
    cmds:
      - echo 'Running Game'
      - odin run .
    #silent: true
  build:
    cmds:
      - echo 'Building Odin'
      - odin build .
    #silent: true
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
