version: '3'

tasks:
  run:
    cmds:
      - echo 'Building Odin'
      - odin run .
      - cat log.txt
    #silent: true    
  build:
    cmds:
      - echo 'Building Odin'
      - odin run .
      - cat log.txt
      - rm log.txt
    #silent: true    
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
